name: flutter_product_carousel
description: This package creates a user-friendly product carousel with images, indicators, and navigation buttons. Users can easily preview the images in a 360° view
version: 0.0.4
homepage: https://github.com/noorj-in/flutter_product_carousel
repository: https://github.com/noorj-in/flutter_product_carousel

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  extended_image: ^8.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

