name: flutter_product_carousel
description: This package is used to create a product carousel with a images, indicators, favorite button and navigation buttons. It is a simple and easy to use package and you can able to see the preview of images in the product carousel.
version: 0.0.1
homepage: https://github.com/noorj-in/flutter_product_carousel
repository: https://github.com/noorj-in/flutter_product_carousel

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^4.2.1
  extended_image: ^8.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

